const projects={
professional:[
['rotary','Rotary Cylindrical Cleaner - Assembly Design','assets/projects/rotary-cleaner.jpg','Rotary cleaning of internal cylindrical bore surfaces.','Designed the cylindrical housing, internal drive gear train, and top mounting flange with bolt hole pattern.','Design Engineer | Tech Valley, Islamabad'],
['drone-lock','Drone Locking System - Mechanism Design','assets/projects/drone-locking.jpg','Secure a drone payload in position.','Designed the locking arms, guide pin, compression spring assembly, and mounting flange.','Design Engineer | Tech Valley, Islamabad'],
['rack','Drone Deployment Rack - Multi-Cell System','assets/projects/drone-rack.jpg','Sequential deployment from a modular multi-cell frame.','Designed the deployment station grid and sliding drive mechanism for sequential drone release.','Design Engineer | Tech Valley, Islamabad'],
['stair','Folding Stair & Platform Mechanism - Vehicle-Mounted Assembly','assets/projects/folding-stair-drawing.jpg','Vehicle mounted folding access system.','Prepared the mechanism, supports, locks, views, BOM, tolerance notes, and fabrication details.','Design Engineer | Tech Valley, Islamabad'],
['fence','Perimeter Fencing Rig - Vehicle-Mounted Assembly','assets/projects/fence-rig.jpg','Mechanized fence-laying system replacing manual perimeter marking.','Designed the full vehicle-mounted assembly integrating storage racks, fence-roll feed reels, and the rear picket driving rail.','Design Engineer | Tech Valley, Islamabad'],
['hammer','Automatic Hammer & Rail Mechanism - Fence-Post Driver','assets/projects/fence-rig.jpg','Automated picket-driving unit that replaces manual hammering in the field.','Designed the hydraulic hammer, guide rail, and actuator-pin linkage that drive fence posts into the ground.','Design Engineer | Tech Valley, Islamabad'],
['radar','Radar Locking Mechanism','assets/projects/radar-locking.jpg','Securely hold and position a drone payload using a mechanically actuated locking arrangement.','Developed the locking mechanism assembly with locking arms, guide elements, spring-loaded components, and a mounting interface for reliable engagement and release.','Design Engineer | Tech Valley, Islamabad']],
solidworks:[
['housing','Housing Design','assets/projects/housing.jpg','Head housing with motor mount interface, and bolt-hole pattern.','SolidWorks component design.','NUST College of EME | Internship'],
['afsd-frame','AFSD Machine Frame & Table Assembly Design','assets/projects/afsd-machine.jpg','Complete structural frame and worktable with motor mounting, linear guides, and base support.','SolidWorks assembly design.','HITEC University Taxila | Final Year Project'],
['bearing','Bearing & Pulley Housing Design','assets/projects/bearing-pulley.jpg','Bearing and pulley housing assembly sized to standard bearing tolerances.','SolidWorks power transmission.','NUST College of EME | Internship'],
['fixture','Bolted Clamp Plate Fixture','assets/projects/fixture.jpg','Bolted clamp-plate fixture with an adjustable bolt hole pattern for workpiece alignment.','SolidWorks fixture design.','NUST College of EME | Internship'],
['milling','Vertical Milling Machine Head','assets/projects/afsd-machine.jpg','Vertical milling machine head and related components modelled for FYP understanding.','SolidWorks university project.','HITEC University Taxila | Final Year Project'],
['bracket','Machined Bracket Component','assets/projects/machined-bracket.jpg','Mounting bracket with stepped faces and a central bore, prepared for VMC machining.','SolidWorks machined component.','NUST College of EME | Internship'],
['tailstock','Tail Stock of Lathe Machine','assets/projects/tailstock.jpg','Manual hand tail stock assembly modelled for lathe machine operations.','SolidWorks semester project.','HITEC University Taxila | Semester Project']],
creo:[
['flange','Flange Coupling Assembly Design with Fastener Pattern','assets/projects/creo-part.jpg','Bolt-hole fastener pattern and shaft interface modelled in PTC Creo.','Assembly design.','NUST Internship'],
['profile','Profile-Milled Component Part Design','assets/projects/creo-part.jpg','Stepped bores and a chamfered profile prepared for CNC machining.','Part design.','NUST Internship'],
['manufacturing','CNC Manufacturing Setup Volume Milling Operation','assets/projects/creo-manufacturing.jpg','Volume-milling setup and toolpath generation in PTC Creo Manufacturing.','Manufacturing setup.','NUST Internship'],
['code','Generated NC Code (G-code / M-code)','assets/projects/cnc-code.jpg','NC program generated from the PTC Creo manufacturing operation.','CNC programming.','NUST Internship']]
};
projects.afsd=['afsd','Friction-Based Metal Printing Machine (AFSD)','assets/projects/afsd-machine.jpg','Manual desktop Additive Friction Stir Deposition machine for AA6061 aluminium, completed at HITEC University Taxila.','Complete SolidWorks assembly; static structural analysis; vibration and frequency analysis; successful AFSD deposition in Pakistan. Verified portfolio results: +4% hardness, +46.2% compression-strength improvement, first natural frequency 24.84 Hz.','HITEC University Taxila | Final Year Project'];
function card(p,label){return `<article class="card reveal"><img src="${p[2]}" alt="${p[1]}" loading="lazy"><div class="card-body"><span class="tag">${label}</span><h3>${p[1]}</h3><p>${p[3]}</p><button class="textbtn modal-open" data-project="${p[0]}">View Project →</button></div></article>`}
document.querySelector('#professional-grid').innerHTML=projects.professional.map(p=>card(p,'SolidWorks · Tech Valley')).join('');
document.querySelector('#solidworks-grid').innerHTML=projects.solidworks.map(p=>card(p,'SolidWorks')).join('');
document.querySelector('#creo-grid').innerHTML=projects.creo.map(p=>card(p,'PTC Creo / CNC')).join('');
const all=[...projects.professional,...projects.solidworks,...projects.creo,projects.afsd];const modal=document.querySelector('#modal');
function openProject(id){const p=all.find(x=>x[0]===id);if(!p)return;document.querySelector('#modal-img').src=p[2];document.querySelector('#modal-img').alt=p[1];document.querySelector('#modal-tag').textContent='PROJECT DETAIL';document.querySelector('#modal-title').textContent=p[1];document.querySelector('#modal-body').innerHTML=`<h4>Purpose / Overview</h4><p>${p[3]}</p><h4>Design Work / Technical Details</h4><p>${p[4]}</p><h4>Project Context</h4><p>${p[5]}</p>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
document.addEventListener('click',e=>{const b=e.target.closest('.modal-open');if(b)openProject(b.dataset.project)});function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelector('#close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
const menu=document.querySelector('#menu'),nav=document.querySelector('#navlinks');menu.onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>reveal.observe(e));
const links=[...nav.querySelectorAll('a')],sections=links.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const spy=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-40% 0px -55%'});sections.forEach(s=>spy.observe(s));
const topBtn=document.querySelector('#top');addEventListener('scroll',()=>topBtn.style.display=scrollY>700?'block':'none');topBtn.onclick=()=>scrollTo({top:0,behavior:'smooth'});
